config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  scope "/admin" do
    resources :users
  end

  get '/about', to: "pages#about"
  get '/contact', to: "pages#contact"
  get '/secret', to: "pages#secret"
  get '/tickets/closed', to: "tickets#closed"

  resources :tickets do
    resources :ticket_messages
  end

  authenticated :user do
    root 'tickets#index', as: :authenticated_root
  end

  root to: "pages#home"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :client, class_name: 'User'
  belongs_to :technician, class_name: 'User'

  has_many :ticket_messages

  enum status: {
    open: 0,
    in_progress: 1,
    pending: 2,
    closed: 3
  }

  validates :subject, presence: true
  validates :content, presence: true

  scope :tickets_open, -> { where.not(status: :closed) }
  scope :tickets_closed, -> { where(status: :closed) }

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @tickets = @tickets.tickets_open
    respond_to do |f|
      f.html { render :index }
      f.json { render json: @tickets}
    end
  end

  def new
    @ticket = Ticket.new
  end

  def show
    @ticket_messages = @ticket.ticket_messages.order(created_at: :desc)
    respond_to do |f|
      f.html { render :show }
      f.json { render json: @ticket}
    end
  end

  def closed
    @tickets = @tickets.tickets_closed
  end

  def create
    @ticket.client = current_user
    @ticket.technician = User.get_technician[0]
    if @ticket.save
      flash[:notice] = "Ticket was successfully created!"
      redirect_to @ticket
    else
      flash[:alert] = "Ticket was not created!"
      render :new
    end
  end

  def edit
  end

  def update
    if @ticket.update(ticket_params)
      flash[:notice] = "Ticket was successfully updated!"
      redirect_to @ticket
    else
      flash[:alert] = "Ticket was not updated!"
      render :edit
    end
  end

  def destroy
    # Admin should only be the ones allowed to delete a ticket
    @ticket.destroy
    redirect_to root_path
  end

  private
    def ticket_params
      params.require(:ticket).permit(:subject, :status, :content, :client_id, :technician_id)
    end

    def set_ticket
      @ticket = Ticket.find(params[:id])
    end
end

app/views/tickets/_form.html.erb
<%= form_for @ticket, html: { class: 'form-horzontal' } do |f| %>
  <div class="form-group">
    <%= f.label :subject, class: 'label-control' %>
    <%= f.text_field :subject, autofocus: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :status, class: 'label-control' %>
    <%= f.select :status, Ticket.statuses.keys, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :content, class: 'label-control' %>
    <%= f.text_area :content, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/tickets/_tickets.html.erb
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Ticket No.</th>
        <th>Subject</th>
        <th>Status</th>
        <th>Technician</th>
      </tr>
    </thead>
    <tbody>
      <% tickets.each do |ticket| %>
      <tr>
        <td><%= link_to ticket.id, ticket_path(ticket) %></td>
        <td><%= ticket.subject %></td>
        <td><%= ticket.status %></td>
        <td><%= ticket.technician.email %>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/tickets/closed.html.erb
<div class="container">
  <h1>Closed Tickets</h1>
  <%= render partial: 'tickets/tickets', locals: {tickets: @tickets} %>
</div>

app/views/tickets/edit.html.erb
<div class="container">
  <div class="row">
    <h2>Edit Ticket</h2>

    <%= render 'form' %>
  </div>
</div>

app/views/tickets/index.html.erb
<div class="container">
  <h1>Tickets</h1>
  <%#= render partial: 'tickets/tickets', locals: {tickets: @tickets} %>
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Ticket No.</th>
          <th>Subject</th>
          <th>Status</th>
          <th>Technician</th>
        </tr>
      </thead>
      <tbody id="tickets-table">

      </tbody>
    </table>
  </div>
  <div id="ticket-body"></div>
</div>

app/views/tickets/new.html.erb
<div class="container">
  <div class="row">
    <h2>New Ticket</h2>

    <%= render 'form' %>
  </div>
</div>

app/views/tickets/show.html.erb
<div class="container">
  <h3>Subject: <%= @ticket.subject %></h3>
  <hr/>
  <p><strong>
    Ticket# <%= @ticket.id %></strong>
     <%= link_to "<i class='fa fa-pencil-square-o'></i>".html_safe,
                            edit_ticket_path(@ticket), id: "edit-ticket" %>
  </p>
  <p><strong>Status:</strong> <%= @ticket.status %></p>
  <p>Technician: <%= @ticket.technician.email %></p>
  <p><strong>Content:</strong></p>
  <p class="well"><%= @ticket.content %></p>

  <hr/>
  <%= link_to "Add Message", new_ticket_ticket_message_path(@ticket), remote: true, class: "btn btn-info" %><br/><br/>

  <% @ticket_messages.each do |message| %>
    <div class="panel panel-<%= panel_color(message.user, @ticket.technician) %>">
      <div class="panel-heading">
        <p>
        Message by: <%= message.user.email %>
        <% if message.user == current_user %>
           <%= link_to "<i class='fa fa-pencil-square-o'></i>".html_safe,
             edit_ticket_ticket_message_path(@ticket, message), remote: true, class: "pull-right" %>
        <% end %>
        </p>
      </div>
      <div class="panel-body">
        <p><%= message.content %></p>
      </div>
    </div>
  <% end %>
</div>