config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  scope "/admin" do
    resources :users
  end

  get '/about', to: "pages#about"
  get '/contact', to: "pages#contact"
  get '/secret', to: "pages#secret"
  get '/tickets/closed', to: "tickets#closed"

  resources :tickets do
    resources :ticket_messages
  end

  authenticated :user do
    root 'tickets#index', as: :authenticated_root
  end

  root to: "pages#home"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">TickCase</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to "My Tickets", tickets_path %></li>
          <li><%= link_to "New Ticket", new_ticket_path %></li>
          <% if !current_user.client? %>
            <li><%= link_to "Users", users_path %></li>
            <li><%= link_to "Closed", tickets_closed_path %></li>
          <% end %>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to current_user.email, get_path %></li>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/_message.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-dismissible alert-info" id="flash_<%= name %>">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert">&times;</button>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tickcase</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/header' %>
    <%= render 'layouts/message' %>

    <%= yield %>
  </body>
</html>